# For more information about the configurations used
# in this file, please see the GitHub Actions documentation.
#
# https://docs.github.com/en/actions

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check links
        run: ./tests/check_links_from_markdown_files.sh

name: Check links

on:
  schedule:
    - cron: "0 0 * * SAT"
